name: Cypress Tests
on: [push, workflow_dispatch]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
     - name: Setup node
       uses: actions/setup-node@v4
       with:
         node-version: 18
     - run: npm install
     - run: echo ${{ vars.PRIVATE_KEY }}
     - run: PRIVATE_KEY=${{ vars.PRIVATE_KEY }} CYPRESS_baseUrl=${{ vars.CYPRESS_BASEURL }} npm test
