name: Cypress Tests
on: [push, workflow_dispatch]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
     - name: Setup node
       uses: actions/setup-node@v4
       with:
         cache: 'npm'
         node-version: 18
         cache-dependency-path: subdir/package-lock.json
     - run: npm install
     # - run: npx browserslist@latest --update-db
     # - run: echo ${{ vars.PRIVATE_KEY }}
     - run: PRIVATE_KEY=${{ vars.PRIVATE_KEY }} CYPRESS_baseUrl=${{ vars.CYPRESS_BASEURL }} npm test
     # - name: run cypress tests with chrome
     #   uses: cypress-io/github-action@v6
     #   with:
     #      install-command: npm --frozen-lockfile --non-interactive
     #      browser: chrome
     #      spec: tests/e2e/specs
     #   env:
     #    PRIVATE_KEY: ${{ vars.PRIVATE_KEY }}
     #    CYPRESS_baseUrl: ${{ vars.CYPRESS_BASEURL }}
