name: Cypress Tests
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
     - uses: actions/checkout@v4
     - name: Setup node
       uses: actions/setup-node@v4
       with:
         node-version: 18
     - run: npm install
     - run: npm test
